# Generated by Django 4.1.2 on 2022-11-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='unitprice',
            new_name='unit_price',
        ),
    ]
