# Generated by Django 4.1.2 on 2022-12-28 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_unitprice_orderitem_unit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
