# Generated by Django 4.1.2 on 2023-04-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_productimage_image_customerimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerImage',
        ),
    ]
